### ISSUE TITLE
Why font is not centered?

### ISSUE THREAD

**Issue by shinayser** [geordanr/xwing-miniatures-font#61]
Hey guys! I am studying the possibility to develop Startactics 2.0 (for iOS and Android using Flutter).
I am testing your fonts and all seems to working fine, despite this little issue:

![screenshot_1](https://user-images.githubusercontent.com/1146982/45599437-f250ac00-b9c1-11e8-8a89-bdb41f166f68.png)

The red circle is an Avatar and I colored the center widget as a blue box just to show you the problem: **the icon are not centered.** This is happening too for the Scum and Empire icons.

You guys got any clue why this is happening? Is a problem of the font or is something I am missing?
(my first time workign with font icons)

Thank you for your support!

_**Edit: I've checked and the huge majority of the icons never gets centered. I tested with the MaterialIcons font from Google and checked on the FontForge program, and all the MaterialIcons are properly centered inside a box. Anyone can tell me how to perform the same with XWing Icons?**_

**Comment by Hinny** [comment]
Hmm, I think something whent wrong when I made the last changes. I can see what I can do about it.

**Comment by sirjorj** [comment]
I was about to open a new issue but I think this is the same thing I saw.  The ship icons are all over the place vertically.  The TIE/sf dips well below the base line, while the ARC-170 stays well above it.  In the attached examples, the red line is something I have it drawing to show the base line.

![plt_arc170starfighter_rebelalliance_garvendreis](https://user-images.githubusercontent.com/6219508/45933242-a4522000-bf4e-11e8-9775-b2ce9d9175d1.png)
![plt_tiesffighter_firstorder_backdraft](https://user-images.githubusercontent.com/6219508/45933243-a4522000-bf4e-11e8-91f7-34ef7a62defb.png)

As you can see, the difference is pretty bad.  For this case, I am using libgd to render these images.  I am figuring out the largest font size I can use before the glyph's bounding box becomes larger than the pilot rectangle I am drawing it in.  Then, I shrink it to 75% of its size (due to the top and bottom spill offs) and render it, aligning it to the right side.  I'm honestly not sure why the ARC doesn't look right aligned in this test image.  Some look great, but some are just way off (the K-Wing is way too high as well).

**Comment by ScottKarch** [comment]
I've looked into it a few times.  The shapes of the ships are so different.  We're using a character as a graphic image.. the ships have wildly differing proportions.  If we made left right and top bottom boundries..  square ships would be huge and very long or very tall ships would be much smaller.  I guess having a max size for height and width makes sense..   Then do we center smaller ships within the character space?  Left Align?   It seems that no matter what we choose some type of layout will look wrong.
I agree it would be great to standardize them, but I think the standard should be researched first.  I have a feeling it's harder than it sounds.   I hope I'm wrong.

**Comment by sirjorj** [comment]
You are probably correct in that there is no 'right' answer for this.  I revisited my code and figured out a way to work around this.  libgd's font rendering system is a bit tricky but I think i figured it out and am getting good results.

**Comment by ScottKarch** [comment]
I started overlaying different ships on top of each other    Here are 2 characters.  Same size, overlapping and center justified.
![image](https://user-images.githubusercontent.com/19825797/46119796-6c5b0f00-c1d2-11e8-9c12-c9f075d90e66.png)
Here they are right justified
![image](https://user-images.githubusercontent.com/19825797/46119887-df648580-c1d2-11e8-80b2-db69de40920e.png)
and here they are left justified.
![image](https://user-images.githubusercontent.com/19825797/46119909-f4411900-c1d2-11e8-9927-12fb86bc3fce.png)

The Arc 170 and TIE fighter are a pretty extreme example of different ratio ships

**Comment by ScottKarch** [comment]
I do agree that faction logos and many circle tokens etc should be the same size and placement...   That will be relatively easy

**Comment by ScottKarch** [comment]
a couple other comparisons.   Quadjumper and TIE are similar..   while the Arc170 and XWing are very similar too.

**Comment by shinayser** [comment]
Scott i totally agree with you. There is no problem for the ship icons but the other icons should be standardize. How difficult is implement this stuff? I would love to help but I have 0 experiencie in working with fonts.

**Comment by Hinny** [comment]
I don't seem to be able to get time devoted into this. So help would be greatly appreciated! I also had no experience with fonts before creating this font. It's not too hard. I used fontforge which is free. Google "vertically center glyphs in fontforge" or something. Tell us if you have problems.
